### ISSUE TITLE
Please add kubernetes

### ISSUE THREAD

**Issue by nigelmann** [noahboegli/nice-browser-extension#1]

**Comment by noahboegli** [comment]
Before we go ahead and implement, we should consider a discussion on whether the idea of spinning an entire scaled-out infrastructure on the user's computer while he's browsing the web is really necessary/a good idea.

**Comment by noahboegli** [comment]
![image](https://user-images.githubusercontent.com/39568628/160618854-42ff4063-7522-40c5-864e-55d8cba7ff4f.png)

**Comment by nigelmann** [comment]
alright !

F*** u m8 !
